[project]
name = "mcp-server-vector-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.8.0",
    "neo4j>=5.28.1",
    "openai>=1.78.1",
    "sentence-transformers>=4.1.0",
]
